CREATE DATABASE ARGENTINA_PROGRAMA;

CREATE TABLE ASPIRANTE (
        ID INT NOT NULL AUTO_INCREMENT,
		  NOMBRE VARCHAR(50) NOT NULL,
		  CARGO VARCHAR(50) NOT NULL,
		  DESCRIPCION VARCHAR(255) NOT NULL,
		  FOTO VARCHAR(5000),
		  PRIMARY KEY (ID)
		  );

CREATE TABLE USUARIO (
        ID INT NOT NULL AUTO_INCREMENT,
        NOMBRE_IMAGEN VARCHAR(50) NOT NULL,
        USUARIO VARCHAR(50) NOT NULL,
        PASSWORD VARCHAR(1000) NOT NULL,
        ID_ASPIRANTE INT NOT NULL,
		  PRIMARY KEY (ID),
		  FOREIGN KEY (ID_ASPIRANTE) REFERENCES ASPIRANTE(ID)
		  );

CREATE TABLE PROYECTO (
        ID INT NOT NULL AUTO_INCREMENT,
        NOMBRE_PROYECTO VARCHAR(50) NOT NULL,
        FECHA_CREACION DATETIME NOT NULL,
        DESCRIPCION VARCHAR(255) NOT NULL,
        LINK VARCHAR(5000),
        ID_ASPIRANTE INT,
		  PRIMARY KEY (ID),
		  FOREIGN KEY (ID_ASPIRANTE) REFERENCES ASPIRANTE(ID)
		  );

CREATE TABLE IMAGEN_PROYECTO (
        ID INT NOT NULL AUTO_INCREMENT,
        NOMBRE_IMAGEN VARCHAR(50) NOT NULL,
        ID_PROYECTO INT NOT NULL,
		  PRIMARY KEY (ID),
		  FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO(ID)
		  );

CREATE TABLE TIPO_EDUCACION (
        ID INT NOT NULL AUTO_INCREMENT,
        TIPO_EDUCACION VARCHAR(50) NOT NULL,
		  PRIMARY KEY (ID)
		  );

CREATE TABLE EDUCACION (
        ID INT NOT NULL AUTO_INCREMENT,
        TITULO_ESTUDIADO VARCHAR(50) NOT NULL,
        NOMBRE_INSTITUTO VARCHAR (50) NOT NULL,
        ID_TIPO_EDUCACION INT NOT NULL,
        LOGO_INSTITUTO VARCHAR(5000),
        FECHA_INICIO DATETIME NOT NULL,
        FECHA_FIN DATETIME,
        ID_ASPIRANTE INT NOT NULL,
		  PRIMARY KEY (ID),
		  FOREIGN KEY (ID_ASPIRANTE) REFERENCES ASPIRANTE(ID),
		  FOREIGN KEY (ID_TIPO_EDUCACION) REFERENCES TIPO_EDUCACION(ID)
		  );

CREATE TABLE EXPERIENCIA (
        ID INT NOT NULL AUTO_INCREMENT,
        CARGO VARCHAR(50) NOT NULL,
        DESCRIPCION_CARGO VARCHAR(255) NOT NULL,
        NOMBRE_EMPRESA VARCHAR(50) NOT NULL,
        LOGO_EMPRESA VARCHAR(5000),
        FECHA_INICIO DATETIME NOT NULL,
        FECHA_FIN DATETIME, 
        ID_ASPIRANTE INT NOT NULL,
		  PRIMARY KEY (ID),
		  FOREIGN KEY (ID_ASPIRANTE) REFERENCES ASPIRANTE(ID)
		  );

CREATE TABLE TIPO_HABILIDAD (
        ID INT NOT NULL AUTO_INCREMENT,
        TIPO_HABILIDAD VARCHAR(50) NOT NULL,
		  PRIMARY KEY (ID)
		  );

CREATE TABLE HABILIDAD (
        ID INT NOT NULL AUTO_INCREMENT,
        NOMBRE_HABILIDAD VARCHAR(50) NOT NULL,
        ID_TIPO_HABILIDAD INT NOT NULL,
        PORCENTAJE INT NOT NULL,
        ID_ASPIRANTE INT NOT NULL,
		  PRIMARY KEY (ID),
		  FOREIGN KEY (ID_ASPIRANTE) REFERENCES ASPIRANTE(ID),
		  FOREIGN KEY (ID_TIPO_HABILIDAD) REFERENCES TIPO_HABILIDAD(ID)
		  );